version: "3.6"
services:
  dom-based-xss-workshop-level-1:
    container_name:  dom-based-xss-workshop-level-1
    build: ./level1
    restart: unless-stopped
    volumes:
      - ./level1/src:/app
    ports:
      - "3001:3001"

  dom-based-xss-workshop-level-2:
    container_name:  dom-based-xss-workshop-level-2
    build: ./level2
    restart: unless-stopped
    volumes:
      - ./level2/src:/app
    ports:
      - "3002:3002"

  dom-based-xss-workshop-level-3:
    container_name:  dom-based-xss-workshop-level-3
    build: ./level3
    restart: unless-stopped
    volumes:
      - ./level3/src:/app
    ports:
      - "3003:3003"

  dom-based-xss-workshop-level-4:
    container_name: dom-based-xss-workshop-level-4
    build: ./level4
    restart: unless-stopped
    volumes:
      - ./level4/src:/app
    ports:
      - "3004:3004"

  dom-based-xss-workshop-search-with-track-lv-1:
    container_name: dom-based-xss-workshop-search-with-track-lv-1
    build: ./search-with-track-lv-1
    restart: unless-stopped
    volumes:
      - ./search-with-track-lv-1/src:/app
    ports:
      - "30011:30011"

  dom-based-xss-workshop-search-with-track-lv-2:
    container_name: dom-based-xss-workshop-search-with-track-lv-2
    build: ./search-with-track-lv-2
    restart: unless-stopped
    volumes:
      - ./search-with-track-lv-2/src:/app
    ports:
      - "30021:30021"
      
  dom-based-xss-workshop-search-tracker-lv-1:
    container_name:  search-tracker-lv-1
    build: ./search-tracker-lv-1
    restart: unless-stopped
    volumes:
      - ./search-tracker-lv-1/src:/app
    ports:
      - "30012:30012"
  
  dom-based-xss-workshop-search-tracker-lv-2:
    container_name:  search-tracker-lv-2
    build: ./search-tracker-lv-2
    restart: unless-stopped
    volumes:
      - ./search-tracker-lv-2/src:/app
    ports:
      - "30022:30022"


volumes:
  notused: